const generateCommentsObjectScheme = ({
  app_id,
  comments_status_field_id,
  comments_replyToRef_field_id
}) => [
  {
    "type":"property",
    "id":3,
    "property_name":"name",
    "property_type":"field_value",
    "name_space":"name",
    "interpretation":1
  },{
    "type":"property",
    "id":5,
    "property_name":"email",
    "property_type":"field_value",
    "name_space":"email",
    "interpretation":1
  },{
    "type":"property",
    "id":6,
    "property_name":"text",
    "property_type":"field_value",
    "name_space":"text",
    "interpretation":1
  },{
    "type":"property",
    "id":4,
    "property_name":"id",
    "property_type":"variable",
    "variable_type":"current_item"
  },{
    "type":"property",
    "id":8,
    "property_name":"date",
    "property_type":"field_value",
    "name_space":"date"
  },{
    "type":"array",
    "id":2,
    "childs":[
        {
            "type":"property",
            "id":9,
            "property_name":"name",
            "property_type":"field_value",
            "name_space":"name",
            "interpretation":1
        },{
            "type":"property",
            "id":10,
            "property_name":"email",
            "property_type":"field_value",
            "name_space":"email",
            "interpretation":1
        },{
            "type":"property",
            "id":11,
            "property_name":"text",
            "property_type":"field_value",
            "name_space":"text",
            "interpretation":1
        },{
            "type":"property",
            "id":12,
            "property_name":"id",
            "property_type":"variable",
            "variable_type":"current_item"
        },{
            "type":"property",
            "id":13,
            "property_name":"date",
            "property_type":"field_value",
            "name_space":"date"
        },
        {
            "type":"property",
            "id":14,
            "property_name":"reply_to",
            "property_type":"field_value",
            "name_space":"reply_to",
            "interpretation":0
        }
    ],
    "property_name":"replies",
    "app_id": app_id,"filter":[
        {
            "field_id":comments_status_field_id,
            "data_type":"radio_button",
            "valuesArray":["1"],
            "search_type":"equal_or",
            "selected_search_option_variable":"Value"
        },{
            "field_id":comments_replyToRef_field_id,
            "data_type":"item_ref",
            "valuesArray":[],
            "search_type":"equal_or",
            "selected_search_option_variable":"Variable",
            "input_type":"variable",
            "input_value":"current_item"
        }
    ]
  }
];

export default generateCommentsObjectScheme;